In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV,RandomizedSearchCV 
from sklearn.preprocessing import StandardScaler  
from sklearn.preprocessing import LabelEncoder,StandardScaler
from sklearn.metrics import confusion_matrix,accuracy_score,precision_score,recall_score,f1_score,classification_report

In [2]:
df=pd.read_csv(r"C:\Users\i7\Downloads\credit_card_fraud_balanced.csv")
df.head()

,amount,transaction_hour,merchant_category,card_type,transaction_channel,location,distance_from_home_km,prev_transactions_24hr,card_age_months,customer_age,credit_score,account_status,is_fraud
0,14.44,11,Dining,Mastercard,Contactless,Ahmedabad,0.67,5,80,26,637,Active,0
1,185.75,12,Grocery,Mastercard,POS,Bengaluru,4.28,7,61,49,668,Active,0
2,245.32,7,Grocery,Amex,POS,Kolkata,7.74,4,86,38,628,New,0
3,304.05,9,Grocery,Mastercard,Online,Kolkata,10.00,3,62,30,676,Active,0
4,255.64,16,Healthcare,Mastercard,Online,Foreign,17.64,1,24,31,566,Active,0

In [3]:
df.isnull().sum()

amount                    0
transaction_hour          0
merchant_category         0
card_type                 0
transaction_channel       0
location                  0
distance_from_home_km     0
prev_transactions_24hr    0
card_age_months           0
customer_age              0
credit_score              0
account_status            0
is_fraud                  0
dtype: int64

In [4]:
df.drop_duplicates(inplace=True)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6230 entries, 0 to 6229
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   amount                  6230 non-null   float64
 1   transaction_hour        6230 non-null   int64
 2   merchant_category       6230 non-null   object
 3   card_type               6230 non-null   object
 4   transaction_channel     6230 non-null   object
 5   location                6230 non-null   object
 6   distance_from_home_km   6230 non-null   float64
 7   prev_transactions_24hr  6230 non-null   int64
 8   card_age_months         6230 non-null   int64
 9   customer_age            6230 non-null   int64
 10  credit_score            6230 non-null   int64
 11  account_status          6230 non-null   object
 12  is_fraud                6230 non-null   int64
dtypes: float64(2), int64(6), object(5)
memory usage: 632.9+ KB

In [6]:
la=LabelEncoder()
df["merchant_category"]=la.fit_transform(df["merchant_category"])
df["card_type"]=la.fit_transform(df["card_type"])
df["transaction_channel"]=la.fit_transform(df["transaction_channel"])
df["location"]=la.fit_transform(df["location"])
df["account_status"]=la.fit_transform(df["account_status"])

In [7]:
df.head()

,amount,transaction_hour,merchant_category,card_type,transaction_channel,location,distance_from_home_km,prev_transactions_24hr,card_age_months,customer_age,credit_score,account_status,is_fraud
0,14.44,11,1,1,1,0,0.67,5,80,26,637,0,0
1,185.75,12,6,1,4,1,4.28,7,61,49,668,0,0
2,245.32,7,6,0,4,8,7.74,4,86,38,628,2,0
3,304.05,9,6,1,3,8,10.00,3,62,30,676,0,0
4,255.64,16,7,1,3,5,17.64,1,24,31,566,0,0

In [8]:
df

,amount,transaction_hour,merchant_category,card_type,transaction_channel,location,distance_from_home_km,prev_transactions_24hr,card_age_months,customer_age,credit_score,account_status,is_fraud
0,14.44,11,1,1,1,0,0.67,5,80,26,637,0,0
1,185.75,12,6,1,4,1,4.28,7,61,49,668,0,0
2,245.32,7,6,0,4,8,7.74,4,86,38,628,2,0
3,304.05,9,6,1,3,8,10.00,3,62,30,676,0,0
4,255.64,16,7,1,3,5,17.64,1,24,31,566,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6225,82.46,15,3,3,1,6,9.28,4,103,42,558,0,0
6226,27.77,13,1,3,3,3,4.97,5,72,62,592,0,0
6227,119.36,10,9,3,1,4,6.57,6,73,61,642,0,0
6228,354.73,16,10,3,2,5,10.97,1,8,41,509,0,1
6229,23.06,9,4,3,2,8,28.64,7,27,39,670,0,0

In [9]:
x=df.drop(columns=["is_fraud"])
y=df["is_fraud"]

In [10]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42,stratify=y)

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6230 entries, 0 to 6229
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   amount                  6230 non-null   float64
 1   transaction_hour        6230 non-null   int64
 2   merchant_category       6230 non-null   int64
 3   card_type               6230 non-null   int64
 4   transaction_channel     6230 non-null   int64
 5   location                6230 non-null   int64
 6   distance_from_home_km   6230 non-null   float64
 7   prev_transactions_24hr  6230 non-null   int64
 8   card_age_months         6230 non-null   int64
 9   customer_age            6230 non-null   int64
 10  credit_score            6230 non-null   int64
 11  account_status          6230 non-null   int64
 12  is_fraud                6230 non-null   int64
dtypes: float64(2), int64(11)
memory usage: 632.9 KB

In [30]:
# data scaling 
scalar=StandardScaler() 
x_train_scale=scalar.fit_transform(x_train)
x_test_scale=scalar.transform(x_test)

In [39]:
para_grid={"max_depth":np.arange(2,30,5),
          "n_estimators":np.arange(100,400,50)}

In [40]:
tuning_model=RandomForestClassifier(random_state=42)

In [41]:
grid_search=GridSearchCV(param_grid=para_grid,
                        estimator=tuning_model,
                        cv=5,
                        n_jobs=-1,
                        scoring='r2',
                        verbose=1) 

grid_search.fit(x_train,y_train)

Fitting 5 folds for each of 36 candidates, totalling 180 fits

GridSearchCV(cv=5, estimator=RandomForestClassifier(random_state=42), n_jobs=-1,
             param_grid={'max_depth': array([ 2,  7, 12, 17, 22, 27]),
                         'n_estimators': array([100, 150, 200, 250, 300, 350])},
             scoring='r2', verbose=1)

In [32]:
grid_search.best_params_

{'max_depth': np.int64(14), 'n_estimators': np.int64(350)}

In [33]:
model=grid_search.best_estimator_

In [36]:
y_pred=model.predict(x_test)
precision_score(y_test,y_pred)

0.9647058823529412

In [38]:
y_pred=model.predict(x_test)
precision_score(y_test,y_pred)

0.9647058823529412

## df.head()

In [23]:

amount=int(input                ("Plears Enter amount  .....             :"))
transaction_hour=int(input      ("Plears Enter transaction_hour.....     :"))
merchant_category=int(input     ("Plears Enter merchant_category         :"))
card_type=int(input             ("Plears Enter card_type  .....          :"))
transaction_channel=int(input   ("Plears Enter transaction_channel       :"))
location=int(input              ("Plears Enter location                  :"))
distance_from_home_km=int(input (" Plears Enter distance_from_home_km    :"))
prev_transactions_24hr=int(input(" Plears Enter prev_transactions_24hr   :"))
card_age_months=int(input       (" Plears Enter card_age_months          :"))
customer_age=int(input          (" Plears Enter customer_age             :"))
credit_score=int(input          (" Plears Enter credit_score             :"))
account_status=int(input        (" Plears Enter account_status           :"))

pre_model = model.predict([[
    amount,
    transaction_hour,
    merchant_category,
    card_type,
    transaction_channel,
    location,
    distance_from_home_km,
    prev_transactions_24hr,
    card_age_months,
    customer_age,
    credit_score,
    account_status
]])
if pre_model == 0:
    print("no is not Fraud")
else:
    print("YES is_fraud")

Plears Enter amount  .....             : 14
Plears Enter transaction_hour.....     : 11
Plears Enter merchant_category         : 6
Plears Enter card_type  .....          : 1
Plears Enter transaction_channel       : 0
Plears Enter location                  : 1
 Plears Enter distance_from_home_km    : 20
 Plears Enter prev_transactions_24hr   : 1
 Plears Enter card_age_months          : 10
 Plears Enter customer_age             : 22
 Plears Enter credit_score             : 100
 Plears Enter account_status           : 2

YES is_fraud